apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: bWloaXJwYXRlbDkxMQ== #base64 of mihirpatel911
  mongo-root-password: UXdlcnR5QDEyMzQ1 #base64 of Qwerty@12345
